# Generated by Django 4.2 on 2023-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
    ]
