# Generated by Django 4.2 on 2023-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadores', '0002_cliente_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dia',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='duracao',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='celular',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='horario',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='servicos',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='shopID',
            new_name='shopId',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='valorPagar',
            new_name='toPay',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='horaInicio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='minuto',
        ),
    ]
