# Generated by Django 4.2 on 2023-05-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadores', '0003_rename_dia_cliente_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='barberID',
            new_name='barberId',
        ),
    ]
