# Generated by Django 4.2 on 2023-04-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('diaCriado', models.DateField()),
                ('diaPago', models.DateField()),
                ('criadoPor', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('formaDePagamento', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=255)),
            ],
        ),
    ]
