# Generated by Django 4.2 on 2023-04-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_user_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='serviceList',
        ),
    ]
