# Generated by Django 4.2 on 2023-05-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_shopproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproducts',
            old_name='Produtos',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='shopproducts',
            old_name='ShopID',
            new_name='shopId',
        ),
        migrations.RenameField(
            model_name='shopsettings',
            old_name='FechaAs',
            new_name='closesAt',
        ),
        migrations.RenameField(
            model_name='shopsettings',
            old_name='PrimeiroDiaDaSemana',
            new_name='firstWeekDay',
        ),
        migrations.RenameField(
            model_name='shopsettings',
            old_name='AbreAs',
            new_name='opensAt',
        ),
        migrations.RenameField(
            model_name='shopsettings',
            old_name='ShopID',
            new_name='shopId',
        ),
        migrations.RenameField(
            model_name='shopsettings',
            old_name='DiasDeTrabalho',
            new_name='workDays',
        ),
    ]
