# Generated by Django 4.2 on 2023-05-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_rename_produtos_shopproducts_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopProducts',
            new_name='ShopProduct',
        ),
        migrations.RenameModel(
            old_name='ShopSettings',
            new_name='ShopSetting',
        ),
    ]
