# Generated by Django 4.2 on 2023-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0002_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='id_barbearia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
