# Generated by Django 4.2 on 2023-04-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0003_lancamento_id_barbearia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='client',
            new_name='cliente',
        ),
    ]
