# Generated by Django 4.2 on 2023-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar', '0004_rename_client_lancamento_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
    ]
