# Generated by Django 4.2 on 2023-04-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telaprincipal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestUser',
        ),
        migrations.DeleteModel(
            name='SendUser',
        ),
    ]
