# Generated by Django 4.2 on 2023-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_user_servicelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopID', models.IntegerField()),
                ('BarbeiroId', models.IntegerField()),
                ('Serviços', models.TextField()),
            ],
        ),
    ]
