# Generated by Django 4.2 on 2023-05-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_barberusersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barberusersetting',
            old_name='BarbeiroId',
            new_name='barberId',
        ),
        migrations.RenameField(
            model_name='barberusersetting',
            old_name='Serviços',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='barberusersetting',
            old_name='ShopID',
            new_name='shopId',
        ),
    ]
