# Generated by Django 4.2 on 2023-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0002_remove_usuario_name_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='accessType',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='shopId',
            field=models.IntegerField(default=0),
        ),
    ]
