# Generated by Django 4.2 on 2023-06-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0003_alter_usuario_accesstype_alter_usuario_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField()),
                ('barberId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('services', models.TextField()),
                ('date', models.DateField()),
                ('schedule', models.TimeField(default='00:00')),
                ('duration', models.CharField(max_length=5)),
                ('toPay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('diaCriado', models.DateField()),
                ('diaPago', models.DateField()),
                ('criadoPor', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('formaDePagamento', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=255)),
                ('id_barbearia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('field_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField()),
                ('products', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField()),
                ('opensAt', models.TimeField()),
                ('closesAt', models.TimeField()),
                ('workDays', models.CharField(max_length=255)),
                ('firstWeekDay', models.CharField(max_length=255)),
            ],
        ),
    ]
