# Generated by Django 4.2 on 2023-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0004_cliente_lancamento_shop_shopproduct_shopsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProduct',
        ),
        migrations.DeleteModel(
            name='ShopSetting',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='field_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='shop',
            name='closesAt',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='shop',
            name='firstWeekDay',
            field=models.CharField(default='sun', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='opensAt',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='shop',
            name='workDays',
            field=models.CharField(default='mon,tue,wed,thu,fri', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(default='Nome Barbearia', max_length=255),
        ),
    ]
