# Generated by Django 4.2 on 2023-06-03 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area_barbeiro', '0005_delete_shopproduct_delete_shopsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('createDate', models.DateField()),
                ('payDate', models.DateField()),
                ('createdBy', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('paymentType', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=255)),
                ('shopId', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
    ]
