# Generated by Django 4.2 on 2023-06-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0006_payment_rename_cliente_client_rename_usuario_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberusersetting',
            name='shopId',
        ),
    ]
