# Generated by Django 4.2 on 2023-06-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0007_remove_barberusersetting_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hasPayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='wasPresent',
            field=models.BooleanField(default=False),
        ),
    ]
