# Generated by Django 4.2 on 2023-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0008_client_haspayed_client_waspresent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
