# Generated by Django 4.2 on 2023-06-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_barbeiro', '0009_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
